samples:
  Barnyard_JRBW3_Nov23_16k_2:                                                                         # Change the name of your sample here
    fastq_path:
      /cfs/klemming/projects/snic/snic2022-23-547/marek/pepe_human_barnyard_P30507/P30507/P30507_1002/02-FASTQ/240126_A01901_0272_BHW3W5DRX3                                        # Modify path to fastq files here
    barcodes:                                                                            # Define your different antibody barcodes here
    #       H3K27ac GTGATGCT
      TGCCTTCT: H3K27ac
      CCTATAGC: H3K27ac
      GTACATGC: H3K27ac
      ACTCCAGA: H3K27ac
      AGGTCAAC: H3K27ac
      CAACGACT: H3K27ac
      GCAGAGAA: H3K27ac
      CACTCGAT: H3K27ac
      ACATCCGT: H3K27ac
      GCCTTCAT: H3K27ac
      CACTGAGA: H3K27ac
      GTACGGTT: H3K27me3
      TCCTCTAG: H3K27me3
      CGTTATCG: H3K27me3
      AGCGAACA: H3K27me3
      GTAGTCCA: H3K27me3
      AGGTTGCA: H3K27me3
      AGTCTGGT: H3K27me3
      AGTTCCTG: H3K27me3
      GTCTAGCA: H3K27me3
      GAAGGCAT: H3K27me3
      ACGACACT: H3K27me3
      CTATCAGC: H3K27me3

general:
  tempdir: /cfs/klemming/projects/snic/snic2022-23-547/tmp                                                          # Modify path to a tmp folder already created here
  cellranger_software: /cfs/klemming/projects/snic/snic2022-23-547/bin/cellranger-atac-2.1.0/bin/cellranger-atac                                         # Modify the path to cellranger binaries here
  cellranger_ref: /cfs/klemming/projects/snic/snic2022-23-547/references/cellranger/refdata-cellranger-atac-GRCh38-and-mm10-2020-A-2.0.0   # Modify the path to cellranger reference here
  macs_genome: mm                                                                        # Modify genome for macs2 callpeak
