samples:
  BARNYARD_1_hs:
    fastq_path:
      /proj/snic2022-23-547/private/marek/nanoscope_v2/data                                           # Modify path to fastq files here
    barcodes:                                                                            # Define your different antibody barcodes here
        bcd_1:          CGTTATCG
        bcd_2:          CACTGAGA
        bcd_3:          GTACGGTT
        bcd_4:          CACTCGAT
        bcd_5:          GCCTTCAT
        bcd_6:          ACATCCGT
        bcd_7:          AGCGAACA
        bcd_8:          ATAGAGGC
        bcd_9:          TATAGCCT
        bcd_10:         TCCTCTAG
        bcd_11:         CCTATCCT
general:
  tempdir: /proj/snic2022-23-547/nobackup/tmp                                                          # Modify path to a tmp folder already created here
  cellranger_software: /sw/bioinfo/Chromium-cellranger-ATAC/2.1.0/rackham/cellranger-atac                                         # Modify the path to cellranger binaries here
  cellranger_ref: /crex/data/Chromium/cellranger-ATAC-data/2.0.0/rackham/refdata-cellranger-arc-GRCh38-2020-A-2.0.0/
  macs_genome: hs